### ISSUE TITLE
Please add support for Android/IOS devices

### ISSUE THREAD

**Issue by alecadavid** [ufna/VaQuoleUI#17]
This is the log error:

```
LogPlayLevelisplay: UnrealBuildTool: E:\projects\unreal Engine\KingdomOfGuardians\trunk\Plugins\VaQuoleUI\Source\VaQuoleUIPlugin\Private\VaQuoleUIPluginPrivatePCH.h(18,9) : fatal error: 'AllowWindowsPlatformTypes.h' file not found
LogPlayLevelisplay: UnrealBuildTool: #include "AllowWindowsPlatformTypes.h"
LogPlayLevelisplay: UnrealBuildTool: ^
LogPlayLevelisplay: UnrealBuildTool: 1 error generated.
LogPlayLevelisplay: UnrealBuildTool: -------- End Detailed Actions Stats -----------------------------------------------------------
LogPlayLevelisplay: UnrealBuildTool: ERROR: UBT ERROR: Failed to produce item: E:\projects\unreal Engine\KingdomOfGuardians\trunk\Plugins\VaQuoleUI\Binaries\Android\VaQuoleUIPlugin-Static-armv7.a
LogPlayLevelisplay: UnrealBuildTool: Cumulative action seconds (8 processors): 0.00 building projects, 8.40 compiling, 0.00 creating app bundles, 0.00 generating debug info, 0.00 linking, 0.00 other
LogPlayLevelisplay: UnrealBuildTool: UBT execution time: 11.83 seconds
LogPlayLevelisplay: CommandUtils.Run: Run: Took 11.9360886s to run UnrealBuildTool.exe
LogPlayLevelisplay: BuildCommand.Execute: ERROR: BUILD FAILED
LogPlayLevelisplay: Program.Main: ERROR: AutomationTool terminated with exception:
LogPlayLevelisplay: Program.Main: ERROR: Exception in AutomationTool: Command failed (Result:2): C:\Program Files\Unreal Engine\4.3\Engine\Binaries\DotNET\UnrealBuildTool.exe KingdomOfGuardians Android Development "E:\projects\unreal Engine\KingdomOfGuardians\trunk\KingdomOfGuardians.uproject" -noxge -rocket. See logfile for details: 'UnrealBuildTool.txt' 
LogPlayLevelisplay: Stacktrace: at AutomationTool.CommandUtils.RunAndLog(String App, String CommandLine, String Logfile, Int32 MaxSuccessCode, String Input, ERunOptions Options)
LogPlayLevelisplay: at AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, String UBTExecutable, String CommandLine, String LogName)
LogPlayLevelisplay: at AutomationTool.UE4Build.BuildWithUBT(String ProjectName, String TargetName, UnrealTargetPlatform TargetPlatform, String Config, String UprojectPath, Boolean ForceMonolithic, Boolean ForceNonUnity, Boolean ForceDebugInfo, Boolean ForceFlushMac, Boolean DisableXGE, String InAddArgs, Boolean ForceUnity)
LogPlayLevelisplay: at AutomationTool.UE4Build.Build(BuildAgenda Agenda, Nullable`1 InDeleteBuildProducts, Boolean InUpdateVersionFiles, Boolean InForceNoXGE, Boolean InForceNonUnity, Boolean InForceUnity)
LogPlayLevelisplay: at Project.Build(BuildCommand Command, ProjectParams Params, Int32 WorkingCL)
LogPlayLevelisplay: at BuildCookRun.DoBuildCookRun(ProjectParams Params)
LogPlayLevelisplay: at BuildCommand.Execute()
LogPlayLevelisplay: at AutomationTool.Automation.Execute(List`1 CommandsToExecute, CaselessDictionary`1 Commands)
LogPlayLevelisplay: at AutomationTool.Automation.Process(String[] CommandLine)
LogPlayLevelisplay: at AutomationTool.Program.MainProc(Object Param)
LogPlayLevelisplay: at AutomationTool.InternalUtils.RunSingleInstance(MainProc Main, Object Param)
LogPlayLevelisplay: at AutomationTool.Program.Main()
LogPlayLevelisplay: Program.Main: ERROR: Command failed (Result:2): C:\Program Files\Unreal Engine\4.3\Engine\Binaries\DotNET\UnrealBuildTool.exe KingdomOfGuardians Android Development "E:\projects\unreal Engine\KingdomOfGuardians\trunk\KingdomOfGuardians.uproject" -noxge -rocket. See logfile for details: 'UnrealBuildTool.txt' 
LogPlayLevelisplay: ProcessManager.KillAll: Trying to kill 0 spawned processes.
LogPlayLevelisplay: Program.Main: AutomationTool exiting with ExitCode=1
LogPlayLevelisplay: Domain_ProcessExit
LogPlayLevelisplay: ProcessManager.KillAll: Trying to kill 0 spawned processes.
LogPlayLevelisplay: copying UAT log files...
LogPlayLevelisplay: RunUAT.bat ERROR: AutomationTool was unable to run successfully.
LogPlayLevelisplay: BUILD FAILED
```

Thanks a lot

**Comment by XC3S** [comment]
the same problem exists for linux
